const logs = [
    {
      captainName: "Picard",
      title: "Courage",
      post: "Courage can be an emotion too.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 100,
    },
    {
      captainName: "Ahab",
      title: "Whale",
      post: "By heavens man, we are turned round and round in this world, like yonder windlass, and fate is the handspike.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 20,
    },
    {
      captainName: "Sarah Lance",
      title: "Vandal Savage",
      post: "I’d tell you to go to hell, but you’d probably just feel at home there.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 0,
    },{
        captainName: "Archer",
        title: "Enterprise",
        post: "Exploring space, one star at a time.",
        mistakesWereMadeToday: false,
        daysSinceLastCrisis: 150,
      },
      {
        captainName: "Adama",
        title: "Galactica",
        post: "We will find Earth, no matter what it takes.",
        mistakesWereMadeToday: false,
        daysSinceLastCrisis: 300,
      },
      {
        captainName: "Picard",
        title: "Diplomacy",
        post: "Sometimes the best solution is not to fight, but to talk.",
        mistakesWereMadeToday: false,
        daysSinceLastCrisis: 250,
      },
      {
        captainName: "Sisko",
        title: "Deep Space Nine",
        post: "Living on the edge of the final frontier.",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 7,
      },
      {
        captainName: "Hunt",
        title: "Andromeda",
        post: "Restoring the Systems Commonwealth, one world at a time.",
        mistakesWereMadeToday: false,
        daysSinceLastCrisis: 100,
      },
      {
        captainName: "Riker",
        title: "Titan",
        post: "Exploring new frontiers beyond the Federation.",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 15,
      },
        {
          captainName: "Jane-way",
          title: "Prodigy",
          post: "I am me",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 70,
        },
        {
          captainName: "Riker",
          title: "Second in Command",
          post: "Commander Riker reporting for duty.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 40,
        },
        {
          captainName: "Kirk",
          title: "Boldly Go",
          post: "To boldly go where no one has gone before.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 150,
        },
        {
          captainName: "Janeway",
          title: "Voyager",
          post: "We're stranded in the Delta Quadrant, and coffee's running low.",
          mistakesWereMadeToday: true,
          daysSinceLastCrisis: 5,
        },
        {
          captainName: "Archer",
          title: "Enterprise",
          post: "These are the voyages of the starship Enterprise.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 80,
        },
        {
          captainName: "Sisko",
          title: "Deep Space Nine",
          post: "Welcome to Bajor. Your adventure begins here.",
          mistakesWereMadeToday: true,
          daysSinceLastCrisis: 10,
        },
        {
          captainName: "Picard",
          title: "Engage",
          post: "Make it so, Number One.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 120,
        },
        {
          captainName: "Spock",
          title: "Vulcan Logic",
          post: "The needs of the many outweigh the needs of the few.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 200,
        },
        {
          captainName: "Geordi",
          title: "La Forge",
          post: "I can see more than most people. My visor is an advantage.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 90,
        },
        {
          captainName: "Uhura",
          title: "Communications Officer",
          post: "Hailing frequencies open, Captain.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 60,
        },
        {
          captainName: "Khan",
          title: "Wrath of Khan",
          post: "I am Khan, and I will have my revenge.",
          mistakesWereMadeToday: true,
          daysSinceLastCrisis: 2,
        },
        {
          captainName: "Q",
          title: "Omnipotent",
          post: "I am Q, and I am everywhere at once.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 999,
        },
        {
          captainName: "Chakotay",
          title: "Voyager First Officer",
          post: "We're a long way from home, but we'll get there.",
          mistakesWereMadeToday: true,
          daysSinceLastCrisis: 7,
        },
        {
          captainName: "Seven of Nine",
          title: "Borg No More",
          post: "I am Seven of Nine, Tertiary Adjunct of Unimatrix 01.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 30,
        },
        {
          captainName: "Pike",
          title: "Discovery",
          post: "The future is uncertain, but we'll face it together.",
          mistakesWereMadeToday: true,
          daysSinceLastCrisis: 15,
        },
        {
          captainName: "Kira",
          title: "Bajoran Resistance",
          post: "The fight for Bajor continues.",
          mistakesWereMadeToday: true,
          daysSinceLastCrisis: 8,
        },
        {
          captainName: "Neelix",
          title: "Voyager's Chef",
          post: "Today's menu: Leola root stew and Neelix's special sauce.",
          mistakesWereMadeToday: true,
          daysSinceLastCrisis: 3,
        },
        {
          captainName: "Worf",
          title: "Klingon Honor",
          post: "Qapla'! Success and glory to the Empire.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 110,
        },
        {
          captainName: "Guinan",
          title: "Bartender",
          post: "A wise person knows that sometimes it's best to listen.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 240,
        },
        {
          captainName: "Sulu",
          title: "Helmsman",
          post: "Warp factor 5, Mr. Chekov.",
          mistakesWereMadeToday: false,
          daysSinceLastCrisis: 70,
        },
      ];
      
export default logs;